import AuthProvider from "@/contexts/auth.context";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";

import { Toaster } from "@/components/ui/sonner"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
        
        <Toaster />
      </body>
    </html>
  );
}
